/**
 * Keep the language manifest and the offline shell in step with the language files.
 *
 *   node scripts/build-lang.mjs
 *
 * A language is a file now, which is what lets a translation platform edit one. Two things have
 * to follow from that and neither can be left to memory:
 *
 *   - `web/lang/index.json`, which is the list the picker draws and the coverage it prints. It
 *     is generated from the English table so a language cannot advertise a completeness nobody
 *     counted, and cannot appear in the picker at all without a file behind it.
 *   - the service worker's shell, because a file that is fetched at runtime and never cached is
 *     a language that works until the network goes away. Adding a translation and forgetting
 *     this would leave that language quietly falling back to English offline — which is the
 *     designed behaviour for a missing file, and so would look like nothing was wrong.
 *
 * Run it after adding or removing a language. `npm test` checks the result either way, so
 * forgetting is a failed test rather than a bug somebody meets on a train.
 */
import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const langDir = path.join(root, 'web', 'lang');

/** Who each language is, in its own script and in English. Order is the order of the picker. */
const NAMES = {
  en: { native: 'English', english: 'English', dir: 'ltr' },
  es: { native: 'Español', english: 'Spanish', dir: 'ltr' },
  de: { native: 'Deutsch', english: 'German', dir: 'ltr' },
  fr: { native: 'Français', english: 'French', dir: 'ltr' },
  hi: { native: 'हिन्दी', english: 'Hindi', dir: 'ltr' },
  ar: { native: 'العربية', english: 'Arabic', dir: 'rtl' },
  pt: { native: 'Português', english: 'Portuguese', dir: 'ltr' },
  ru: { native: 'Русский', english: 'Russian', dir: 'ltr' },
  id: { native: 'Bahasa Indonesia', english: 'Indonesian', dir: 'ltr' },
  tr: { native: 'Türkçe', english: 'Turkish', dir: 'ltr' },
  it: { native: 'Italiano', english: 'Italian', dir: 'ltr' },
  bn: { native: 'বাংলা', english: 'Bengali', dir: 'ltr' },
  ur: { native: 'اردو', english: 'Urdu', dir: 'rtl' },
  fa: { native: 'فارسی', english: 'Persian', dir: 'rtl' },
  ja: { native: '日本語', english: 'Japanese', dir: 'ltr' },
  ko: { native: '한국어', english: 'Korean', dir: 'ltr' },
  nl: { native: 'Nederlands', english: 'Dutch', dir: 'ltr' },
  pl: { native: 'Polski', english: 'Polish', dir: 'ltr' },
  uk: { native: 'Українська', english: 'Ukrainian', dir: 'ltr' },
  vi: { native: 'Tiếng Việt', english: 'Vietnamese', dir: 'ltr' },
  'zh-CN': { native: '简体中文', english: 'Chinese (Simplified)', dir: 'ltr' },
  'zh-TW': { native: '繁體中文', english: 'Chinese (Traditional)', dir: 'ltr' },
};

const files = (await fs.readdir(langDir))
  .filter((f) => f.endsWith('.json') && f !== 'index.json')
  .map((f) => f.replace(/\.json$/, ''));

const english = JSON.parse(await fs.readFile(path.join(langDir, 'en.json'), 'utf8'));
const enKeys = Object.keys(english);

const unknown = files.filter((c) => !NAMES[c]);
if (unknown.length) {
  console.error(`no name for: ${unknown.join(', ')} — add it to NAMES in this script`);
  process.exitCode = 1;
}

const manifest = [];
for (const code of Object.keys(NAMES)) {
  if (!files.includes(code)) continue;
  const table = JSON.parse(await fs.readFile(path.join(langDir, `${code}.json`), 'utf8'));
  // A key present but empty is not translated; counting it would overstate the language.
  const done = enKeys.filter((k) => typeof table[k] === 'string' && table[k].trim()).length;
  manifest.push({ ...NAMES[code], code, coverage: Math.round((done / enKeys.length) * 100) });
  console.log(`  ${code.padEnd(6)} ${String(done).padStart(3)}/${enKeys.length} keys`);
}

await fs.writeFile(path.join(langDir, 'index.json'), JSON.stringify(manifest, null, 2) + '\n', 'utf8');
console.log(`  index.json  ${manifest.length} languages`);

/* The shell, rewritten between its markers so the rest of the list is left alone. */
const swPath = path.join(root, 'web', 'sw.js');
let sw = await fs.readFile(swPath, 'utf8');
const wanted = ['lang/index.json', ...manifest.map((l) => `lang/${l.code}.json`)];
const block = wanted.map((f) => `  '${f}',`).join('\n');

const START = '  /* languages: generated by scripts/build-lang.mjs */\n';
const END = '  /* end languages */\n';
const already = sw.indexOf(START);
if (already >= 0) {
  sw = sw.slice(0, already) + START + block + '\n' + END + sw.slice(sw.indexOf(END) + END.length);
} else {
  const anchor = "  'core/thumb.js',\n";
  if (!sw.includes(anchor)) throw new Error('cannot find where the shell list ends');
  sw = sw.replace(anchor, anchor + START + block + '\n' + END);
}
await fs.writeFile(swPath, sw, 'utf8');
console.log(`  sw.js       ${wanted.length} language files in the offline shell`);
